---
application:
  name: "image-processing-api"
  project: "Image-Processing-API"
  organization: "QoveryCommunity"
routers:
- name: "main-image-processing-api"
  routes:
  - application_name: "image-processing-api"
    paths:
    - "/*"
